apiVersion: v2
dependencies:
- name: gloo
  repository: https://storage.googleapis.com/solo-public-helm
  version: 1.14.1
- condition: prometheus.enabled
  name: prometheus
  repository: https://prometheus-community.github.io/helm-charts
  tags:
  - monitoring
  version: 15.18.0
- condition: grafana.defaultInstallationEnabled
  name: grafana
  repository: https://grafana.github.io/helm-charts
  tags:
  - monitoring
  version: 6.16.14
- name: gloo-fed
  repository: file:///workspace/solo-projects/install/helm/gloo-fed
  version: 1.14.1
description: A Helm chart for Kubernetes
name: gloo-ee
version: 1.14.1
